<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>cdk</artifactId>
		<groupId>org.richfaces</groupId>
		<version>3.3.4.Final</version>
	</parent>
	<groupId>org.richfaces.cdk</groupId>
	<artifactId>maven-javascript-plugin</artifactId>
	<version>3.3.4.Final-gov4j-1</version>
	<packaging>maven-plugin</packaging>
	<name>YUI Compressor Maven Mojo</name>
	<description>
		To compress (Minify + Ofuscate) Javascript files and CSS files
		(using YUI Compressor from Julien Lecomte) and/or to check
		Javascript files with jslint.
	</description>

	<dependencies>
		 <dependency>
	      <groupId>org.sonatype.plexus</groupId>
	      <artifactId>plexus-build-api</artifactId>
	      <version>0.0.7</version>
	    </dependency>
		<dependency>
			<groupId>rhino</groupId>
			<artifactId>js</artifactId>
<!-- 			<version>1.6R7</version> -->
			<version>1.7R2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
<!-- 			<version>2.0.7</version> -->
			<version>2.2.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-project</artifactId>
<!-- 			<version>2.0.7</version> -->
			<version>2.2.1</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins />
		<finalName>${finalName}</finalName>
	</build>
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-plugin-plugin</artifactId>
			</plugin>
		</plugins>
	</reporting>

	<properties>
		<finalName>${project.artifactId}-${project.version}</finalName>
		<java.src.version>1.8</java.src.version>
		<runtime.log>target/velocity.log</runtime.log>
	</properties>

</project>
